### ISSUE TITLE
Save for later

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#544]
A new option on task page action bar, with "Save for later" label with a save icon. And once it is clicked and saved, it should switch to "Remove from Save for later" with the delete icon. Then when we are on task explorer, it should have a new tab item with the label "Saved for later", with the issues filtered by the saved ones.

We should create a model with a user with many saved issues.

### Why
We should be able to collect issues we're interested in and check later.

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - We should have a button "Save for later"

### Tips
Check our existing models

**Comment by topseySuave** [comment]
Hello @alexanmtz I would like to work on this issue and would appreciate I am assigned to it.

**Comment by alexanmtz** [comment]
Hello @topseySuave, you're now assigned to work on this issue 👍

**Comment by topseySuave** [comment]
Hi @alexanmtz trying to run the server and I am getting this error


```
/Users/gabrielmicah/Development/gitpay/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/gabrielmicah/Development/gitpay/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/Users/gabrielmicah/Development/gitpay/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at Object.<anonymous> (/Users/gabrielmicah/Development/gitpay/config/passport.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```

This is because I do not have the environment variables and adequate credentials for the complete setup, I want to know if I can get the contents of the  .env file for this to work

**Comment by alexanmtz** [comment]
Hello @topseySuave , I think you're missing the step in our README to copy `.env.example` to `.env` to have the env variables set.

**Comment by topseySuave** [comment]
I got it already sorry, thanks.

**Comment by topseySuave** [comment]
Hi, Good day @alexanmtz I have currently added the action button on the frontend and working on actually saving a task in the database,  but I have this issue where I created a migration file as well as the model after running  `sequelize migration:create --name saveTask` and run `npm run migrate` I get only this migration

```
> node migrate.js up

(node:42393) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
20200323014820-create-plan migrating
========
========
```

the new migration file `20200403235735-saveTask` I have gets ignored, please do you know how I can go about this?

Thanks.

**Comment by alexanmtz** [comment]
Hello @topseySuave, can you try to run `npm run migrate` instead?

**Comment by Adekoreday** [comment]
This issue has been fixed in PR #640 once merged
Kindly use the migration update command

**Comment by neeraj542** [comment]
hey! if still not solved, can I work along?

**Comment by Niharika0104** [comment]
I want to work on this @alexanmtz

**Comment by alexanmtz** [comment]
Hey @Niharika0104 , feel free to work on this one and send a PR 👌

**Comment by Niharika0104** [comment]
![Image](https://github.com/user-attachments/assets/65efe1ff-3f13-4dab-8962-ba084fd049e0)
@alexanmtz just wanted to confirm my understanding.. we need to have `save for later` button on every issue present in the issues table right ? and if the issue is marked as `save for later` then it should have `"remove from save for later`" button and should also have `save for later` label on that issue
in the labels filter we need to add `save for later` filter and when we select that label we should see all the issues which has `save for later` label on it right?

**Comment by alexanmtz** [comment]
Hey @Niharika0104 , thanks for sending your questions to clarify this.

You don't need to add a save for later on the issues table; you should add it on the single issue page. And yeah, we will have a new tab of the issues saved for later to be filtered on the issue page.

Let me know if you have any more questions or guidance to complete this.

**Comment by Niharika0104** [comment]
@alexanmtz  sorry for the delay I'm working on it

**Comment by alexanmtz** [comment]
I will close this one
