### ISSUE TITLE
React-intl payment options preference

### ISSUE THREAD

**Issue by arrudaricardo** [worknenjoy/gitpay#585]
Not able to access payment options preference under user profile.

error log:
```
fetch user account error Invariant Violation: [React Intl] An `id` must be provided to format a message.
    at e.exports (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:12:20052)
    at he (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:12:9130)
    at https://gitpay.me/main.f9d5ec44a13605be903c.js:31:303886
    at Array.map (<anonymous>)
    at t.value (https://gitpay.me/main.f9d5ec44a13605be903c.js:31:303787)
    at za (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:45:69163)
    at Ya (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:45:68956)
    at Qs (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:45:104659)
    at _c (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:45:89167)
    at pc (https://gitpay.me/vendors~main.f9d5ec44a13605be903c.js:45:89092)
```

### Level
Low

### Current behavior
Not able to access payment option 

### Expected behavior
Load React Component Payment Option

### Useful links
 https://gitpay.me/#/profile/payment-options

### Screenshot attached
![error](https://user-images.githubusercontent.com/35773631/78178886-fee40a80-7468-11ea-9418-d6b86a73470a.png)

### How to reproduce the user scenario
 - Create a user
- Access User Profile
- Access Payment Option

### What you will need to complete this issue
Extra requirements to complete the task
Debug React-intl

**Comment by alexanmtz** [comment]
Thanks @arrudaricardo to report this issue 🥇

**Comment by alexanmtz** [comment]
Your changes was merged and deployed @arrudaricardo, thanks again for your great contribution 🙏
